name: vegetables-fruits-season
version: 0.1.0.0
github: "githubuser/vegetables-fruits-season"
license: BSD3
author: "Jeremy Fourna"
maintainer: "jeremyfourna@mykolab.com"
copyright: "2018 Jeremy Fourna"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis: Short description of your package
# category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/vegetables-fruits-season#readme>

dependencies:
- base >= 4.8.2.0 && < 5
- scotty >= 0.11 && < 1
- aeson >= 1.2.4.0 && < 2
- blaze-html >= 0.9 && < 1
- clay >= 0.12.2 && < 1
- blaze-markup >= 0.8.2.1 && < 1
- text >= 1.2.3.0 && < 2
- wai-extra >= 3.0.22.0 && < 4

library:
  source-dirs: src

executables:
  vegetables-fruits-season-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vegetables-fruits-season

tests:
  vegetables-fruits-season-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vegetables-fruits-season
